sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t nucoxia/keeperapp .

script:
  - docker run -e CI=true nucoxia/keeperapp npm run test
