sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t nucoxia/keeperapp .

script:
  - docker run -e CI=true nucoxia/keeperapp npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-keeper2"
  env: "Dockerkeeper2-env"
  bucket_name: "elasticbeanstalk-us-east-2-570033759147"
  bucket_path: "docker-keeper2"
  on:
   branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

